import { useEffect, useState } from 'react';
import { Activity, ArrowDownToLine, Check, Layers3 } from 'lucide-react';
import { bytes, duration, remaining, isActive, percent, statusLabels, type Job } from '../types';

export function ChunkPanel({ job }: { job?: Job }) {
  const [page, setPage] = useState(0);
  useEffect(() => setPage(0), [job?.id]);
  const chunks = job?.progress.chunks ?? [];
  const pages = Math.max(1, Math.ceil(chunks.length / 32));
  const visible = chunks.slice(page * 32, (page + 1) * 32);
  const eta = job?.etaSeconds ?? -1;
  return <aside className="detail-panel" aria-label="Таталтын дэлгэрэнгүй"><div className="panel-title"><Activity size={17}/><h2>Таталтын дэлгэрэнгүй</h2><span className="live-dot"/></div>
    {job ? <><div className="detail-heading"><p className="eyebrow">СОНГОСОН ФАЙЛ</p><h3 title={job.filename}>{job.filename}</h3><span className={`status ${job.status}`}>{statusLabels[job.status]}</span></div><div className="detail-percent">{job.progress.total < 0 ? '—' : percent(job).toFixed(1)}<span>%</span><small>нийт татсан</small></div><div className="detail-main-progress progress-track"><div style={{width:`${percent(job)}%`}}/></div><div className="detail-metrics"><div><span>Таталтын хурд</span><strong>{bytes(job.progress.bytesPerSecond)}<small>/s</small></strong></div><div><span>Үлдсэн хугацаа ≈</span><strong>{job.status === 'complete' ? 'Дууссан' : job.status==='paused' ? 'Түр зогссон' : remaining(eta)}</strong></div><div><span>Өнгөрсөн хугацаа</span><strong>{duration(job.elapsedSeconds)}</strong></div><div><span>Татсан хэмжээ</span><strong>{bytes(job.progress.downloaded)}</strong></div></div>
    <div className="chunk-heading"><h3><Layers3 size={15}/> Файлын хэсгүүд</h3><span>{chunks.length} хэсэг</span></div><p className="chunk-explanation">Блок бүр тухайн хэсгийн бодит явцыг харуулна.</p>
    {chunks.length ? <><div className="chunk-grid">{visible.map(c => { const p = c.end > c.start ? Math.min(100,c.downloaded/(c.end-c.start)*100) : 0; return <div className={`chunk-cell ${c.status}`} key={c.id} title={`#${c.id+1}: ${bytes(c.downloaded)} / ${bytes(c.end-c.start)} · ${bytes(c.bytesPerSecond)}/s`}><span style={{height:`${p}%`}}/><strong>{c.status==='complete' ? <Check size={12}/> : String(c.id+1).padStart(2,'0')}</strong></div>; })}</div><div className="chunk-legend"><span><i className="done"/> Дууссан</span><span><i className="working"/> Татаж байна</span><span><i/> Хүлээж байна</span></div><div className="chunk-table"><div className="chunk-table-head"><span>Хэсэг</span><span>Хэмжээ</span><span>Хурд / төлөв</span></div>{visible.map(c => <div className="chunk-row" key={c.id}><strong>#{String(c.id+1).padStart(2,'0')}</strong><span>{bytes(c.downloaded)}<small>/ {bytes(c.end < 0 ? -1 : c.end-c.start)}</small></span><span>{isActive(c.status) ? `${bytes(c.bytesPerSecond)}/s` : statusLabels[c.status] ?? c.status}{c.retries ? <small>{c.retries} дахин оролдсон</small> : null}</span></div>)}</div>{pages > 1 ? <div className="pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Өмнөх</button><span>{page+1} / {pages}</span><button disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}>Дараах</button></div> : null}</> : <div className="chunk-placeholder">{job.sourceKind==='youtube' ? 'YouTube: видео ба аудиог татаж MP4 болгон бэлтгэнэ. Чанар: боломжтой үед 1080p хүртэл.' : 'Сервертэй холбогдсоны дараа хэсгүүд энд харагдана.'}</div>}
    <div className="destination"><span>ХАДГАЛАХ БАЙРШИЛ</span><p>{job.path}</p></div></> : <div className="detail-empty"><div className="empty-orbit"><ArrowDownToLine size={30}/></div><h3>Байт бүрийг хянаарай</h3><p>Таталтаа сонгоод хурд, үлдсэн хугацаа, хэсэг бүрийн явцыг эндээс хараарай.</p><div className="preview-blocks">{Array.from({length:12},(_,i)=><span key={i}/>)}</div></div>}
  </aside>;
}
